name: integration

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, 'branch-*' ]

jobs:
  build:
    runs-on: ubuntu-21.04

    steps:
      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/checkout@v2
        with:
          repository: tmtsoftware/tcs-vslice-0.4
          path: tcs-vslice-0.4

      - uses: laughedelic/coursier-setup@v1
        with:
          jvm: 11
          apps: sbt sbtn
      - uses: coursier/cache-action@v5

      - name: Install Redis
        run: sudo apt-get install redis-server

      - name: Install Kotlin
        run: |
          curl -s https://get.sdkman.io | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          sudo ln -s $(which kotlinc) /usr/local/bin/kotlinc

      - name: Setup OS Libs for TCS Assemblies
        working-directory: tcs-vslice-0.4
        run: ./install.sh

      - name: Build
        working-directory: main/integration
        run: |
          sbtn clean
          sbtn scalafmtCheck

      - name: Tests
        working-directory: main/integration
        run: sbt -DenableFatalWarnings=true "testOnly esw.observing.simulation.TcsSequencerTest"

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
